server: 
    port: 8084
spring:
    kafka:
        bootstrap:
            servers: localhost:9092
logging:
    level:
        ROOT: INFO
edu:
    cefet:
        tcc:
            drugs-files:
                full-list-file-name: filtered_data.csv
                checkpoint-file-name: remaining_drugs.csv
            extraction-historical:
                app-tweets:
                    output-topic: new-filtered-data-test
        twitter:
            auth-token: 
            default-url: https://api.twitter.com/2/tweets/search/recent
            request-limit: 400
